/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PostCourseBodySchema {
  id: number;
  name: string;
  units: {
    id: number;
    name: string;
    topics: {
      id?: number;
      name: string;
      /**
       * When the course is scheduled to start.
       */
      startDate: Date;
      /**
       * When the course is scheduled to start.
       */
      endDate: Date;
      /**
       * When the course is scheduled to start.
       */
      deadDate: Date;
      partialExtend: boolean;
      description: {
        [k: string]: unknown;
      } | null;
      topicTypeId: number;
      questions: {
        id: number;
        problemNumber: number;
        webworkQuestionPath: string;
        weight: number;
        maxAttempts: number;
        optional: boolean;
        courseQuestionAssessmentInfo: null | {
          randomSeedSet: number[];
          additionalProblemPaths: string[];
        };
      }[];
      topicAssessmentInfo: null | {
        duration: number;
        hardCutoff: boolean;
        hideHints: boolean;
        hideProblemsAfterFinish: boolean;
        maxGradedAttemptsPerVersion: number;
        maxVersions: number;
        randomizeOrder: boolean;
        showItemizedResults: boolean;
        showTotalGradeImmediately: boolean;
        versionDelay: number;
      };
    }[];
  }[];
}
