name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install-server
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./server
      - name: eslint-server
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
          eslint_flags: '--ext .tsx,.ts,.js .'
          fail_on_error: true
          workdir: ./server
