name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint / core
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
      # --unsafe-perm Github uses root for install and this will break local dependencies and workflow, using container breaks the entire script
      - run: npm --prefix ./core --unsafe-perm install
      - name: eslint-core
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
          eslint_flags: '--ext .tsx,.ts,.js .'
          fail_on_error: true
          workdir: ./core
