name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm --prefix ./standalone install
      - name: eslint-standalone
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
          eslint_flags: '--ext .tsx,.ts,.js .'
          fail_on_error: true
          workdir: ./standalone
