name: Node.js CI

on: [pull_request]

jobs:
  build:
    name: test / core

    runs-on: ubuntu-latest
      container:
        # Running as a non root user since things in node (like npm install and prepare) behave differently as root
        options: --user 1001

    strategy:
      matrix:
        node-version: [14.15.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm --prefix ./core install
    # Needs to be before the try build step since it prunes dependencies
    # - name: Test
    #   run: npm test
    #   env:
    #     CI: true
    - name: Build
      run: npm --prefix ./core run build
      env:
        REDERLY_PACKAGER_ARCHIVE: false
        # Can't preserve packages because try build will find the node module in the parent directory
        REDERLY_PACKAGER_PRESERVE_NODE_MODULES: false
        CI: false # TODO Linting errors cause the build to fail when CI is true (default)
    - run: npm --prefix ./core prune --production
    - name: Try build
      run: npm --prefix ./core run run:build -- noop
      env:
        DB_SYNC: false
        FAIL_ON_MISSING_CONFIGURATIONS: false
